Options:
  Language: en_US

Loader:
  Hologram-Files:
    - 'plugins/CustomHologramsFolder'

Hologram:
  Interact-Min-Delay: 500
  Options:
    Default-Line-Spacing: 0.25
    Default-View-Distance: 20
    Default-View-Condition: ''
    Default-Refresh-Condition: -1
